import { Product, type IProduct } from "@/lib/types"

const productsData: IProduct[] = [
    {
    "id": "sweet-lime-mosambi",
    "name": "Sweet Lime (Mosambi)",
    "hsCode": "08055000",
    "category": "Fruits",
    "subCategory": "Citrus Fruits",
    "images": {
      "cover": "/products/fruits-sweetlime/image (2).jpeg?height=600&width=800",
      "gallery": ["/products/fruits-sweetlime/image (1).jpeg?height=400&width=600", "/products/fruits-sweetlime/image (3).jpeg?height=400&width=600"]
    },
    "summary": "Juicy, sweet, and mildly acidic Indian Sweet Lime (Mosambi), prized for its refreshing juice and high vitamin C content. Ideal for fresh markets and juice processing industries.",
    "specs": {
      "grade": "A-Grade, Export Quality",
      "keyParameters": {
        "moisture": "Juice Content > 40%",
        "purityOrActives": "Brix > 8°, Acidity 0.5-0.8%",
        "sizeOrLength": "Caliber: 48 / 56 / 64 / 72 fruits per carton",
        "defects": "Free from blemishes, pests, rot, and skin damage",
        "foreignMatter": "Clean, free from dirt and leaves"
      },
      "compliance": {
        "marketMRLs": ["EU", "GCC", "Southeast Asia"],
        "gmo": "Non-GMO",
        "allergens": "None"
      }
    },
    "origin": { "country": "India", "region": "Maharashtra, Andhra Pradesh, Telangana" },
    "packaging": {
      "options": ["10kg CFB cartons", "15kg CFB cartons", "Custom packaging available"],
      "palletization": true,
      "containerLoadability": { "20ft": 10, "40ft": 22 }
    },
    "trade": {
      "moq": "1 x 40ft Reefer Container (approx. 22 MT)",
      "leadTime": "7-10 days from payment confirmation",
      "incoterms": ["FOB JNPT/Mundra", "CFR destination port"],
      "paymentTerms": ["Irrevocable LC at sight", "50% TT Advance, 50% against scanned documents"],
      "inspection": "SGS / APEDA certified packhouse inspection",
      "documents": [
        "Commercial Invoice",
        "Packing List",
        "Bill of Lading",
        "Certificate of Origin",
        "Phytosanitary Certificate",
        "GlobalG.A.P. Certificate",
        "Certificate of Analysis"
      ]
    },
    "certifications": ["APEDA", "GlobalG.A.P."],
    "shelfLife": "30-45 days from harvest under controlled temperature",
    "storage": "Store at 8-10°C with 85-95% relative humidity.",
    "capabilities": { "privateLabel": true, "monthlyCapacityMT": 2000, "samples": "Available by air freight at buyer's cost" },
    "pricing": {
      "currency": "USD",
      "basis": ["FOB", "CFR"],
      "priceOnRequest": true,
      "notes": "Prices quoted based on fruit size (count), packaging, and destination"
    },
    "notes": "Peak harvest season is during the monsoon and post-monsoon months (August-October). Available year-round with seasonal variations."
    },
    {
    id: "banana",
    name: "Banana",
    hsCode: "08039010",
    category: "Fruits",
    subCategory: "Tropical Fruits",
    images: {
      "cover": "/products/fruits-banana/image (2).jpeg?height=600&width=800",
      "gallery": ["/products/fruits-banana/image (1).jpeg?height=400&width=600", "/products/fruits-banana/image (3).jpeg?height=400&width=600"]
    },
    summary: "Premium quality Cavendish bananas, harvested green and packed to meet international standards for ripening at the destination.",
    specs: {
      grade: "A-Grade (Cavendish G9)",
      keyParameters: {
        sizeOrLength: "Length: 18-25 cm, Calibration: 40-48 mm",
        defects: "Free from blemishes, scarring, and pests",
        purityOrActives: "Hands of 4, 5, 6 fingers",
      },
      compliance: {
        marketMRLs: ["GCC", "Iran", "Europe"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra, Andhra Pradesh, Gujarat" },
    packaging: {
      options: ["13.5kg net weight CFB boxes, vacuum bagged"],
      palletization: true,
      containerLoadability: { "20ft": 8, "40ft": 20 },
    },
    trade: {
      moq: "1 x 40ft Reefer Container (20 MT)",
      leadTime: "7-10 days",
      incoterms: ["FOB JNPT/Mundra", "CFR"],
      paymentTerms: ["LC at sight, TT"],
      inspection: "APEDA certified packhouse inspection",
      documents: ["Standard docs + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "Up to 6 weeks under controlled atmosphere",
    storage: "Transported at 13.5°C.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 5000, samples: "On request" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Strict pre-cooling and cold chain management is followed." },
    notes: "Bananas are shipped green to ripen at the destination market.",
  },
  {
    id: "papaya",
    name: "Papaya",
    hsCode: "08072000",
    category: "Fruits",
    subCategory: "Tropical Fruits",
    images: {
      cover: "/products/fruits-papaya/image (1).jpeg?height=600&width=800",
      gallery: ["/products/fruits-papaya/image (2).jpeg?height=400&width=600", "/products/fruits-papaya/image (3).jpeg?height=400&width=600"],
    },
    summary: "Sweet and flavorful papayas, known for their vibrant orange flesh and rich vitamin content. Exported primarily by air.",
    specs: {
      grade: "A-Grade (e.g., Red Lady)",
      keyParameters: {
        sizeOrLength: "Weight 800g - 1500g per fruit",
        defects: "Uniform size and color, free from blemishes and pests",
        purityOrActives: "Brix level > 12",
      },
      compliance: {
        marketMRLs: ["GCC", "Europe"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Andhra Pradesh, Gujarat, Maharashtra" },
    packaging: {
      options: ["3.5kg, 5kg Corrugated Fibreboard (CFB) boxes"],
      palletization: true,
      containerLoadability: { "20ft": 7, "40ft": 16 },
    },
    trade: {
      moq: "500 kg (By Air)",
      leadTime: "3-5 days",
      incoterms: ["FOB Mumbai/Chennai", "CIF/CFR"],
      paymentTerms: ["100% Advance TT for Air shipments"],
      inspection: "APEDA certified packhouse",
      documents: ["Standard docs + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "10-15 days under controlled temperature",
    storage: "Store at 8-12°C.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 200, samples: "On request" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Short shelf life necessitates air shipment for most markets." },
    notes: "Harvested at the right maturity stage for optimal ripening.",
  },
    {
    id: "guava",
    name: "Guava",
    hsCode: "08045030",
    category: "Fruits",
    subCategory: "Tropical Fruits",
    images: {
      cover: "/products/fruits-guava/image (1).jpeg?height=600&width=800",
      gallery: ["/products/fruits-guava/image (2).jpeg?height=400&width=600", "/products/fruits-guava/image (3).jpeg?height=400&width=600"],
    },
    summary: "Aromatic and nutrient-rich tropical guava, available in both white and pink flesh varieties. Known for its high vitamin C content.",
    specs: {
      grade: "A-Grade (e.g., Allahabad Safeda, L-49)",
      keyParameters: {
        sizeOrLength: "150g - 300g per fruit",
        defects: "Smooth skin, uniform shape, free from bruising and pests.",
        purityOrActives: "Brix level > 10",
      },
      compliance: {
        marketMRLs: ["GCC", "Europe", "Malaysia"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra, Uttar Pradesh, Andhra Pradesh" },
    packaging: {
      options: ["3.5kg, 5kg CFB boxes, with individual fruit netting"],
      palletization: true,
      containerLoadability: { "20ft": 7, "40ft": 16 },
    },
    trade: {
      moq: "500 kg (By Air)",
      leadTime: "3-5 days",
      incoterms: ["FOB Mumbai/Delhi", "CFR"],
      paymentTerms: ["100% Advance TT"],
      inspection: "APEDA certified packhouse",
      documents: ["Standard docs + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "10-15 days under controlled temperature",
    storage: "Store at 8-10°C.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 300, samples: "On request" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Pink flesh guava is popular for processing into pulp and juices." },
    notes: "Processed guava pulp is also a significant export product.",
  },
  {
    id: "watermelon",
    name: "Watermelon",
    hsCode: "08071100",
    category: "Fruits",
    subCategory: "Melons",
    images: {
      cover: "/products/fruits-watermelon/image (1).jpeg?height=600&width=800",
      gallery: ["/products/fruits-watermelon/image (2).jpeg?height=400&width=600", "/products/fruits-watermelon/image (3).jpeg?height=400&width=600"],
    },
    summary: "Juicy and sweet watermelons with vibrant red flesh. Harvested at peak ripeness and shipped in refrigerated containers to maintain freshness.",
    specs: {
      grade: "A-Grade (e.g., Sugar Baby)",
      keyParameters: {
        sizeOrLength: "Weight 3kg - 7kg per fruit",
        defects: "Uniform dark green rind, free from cracks and sunscald.",
        purityOrActives: "Brix level > 11, crisp texture",
      },
      compliance: {
        marketMRLs: ["GCC", "Maldives"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra, Andhra Pradesh, Karnataka" },
    packaging: {
      options: ["Packed in large corrugated bins or cartons, approx 20kg"],
      palletization: true,
      containerLoadability: { "20ft": 10, "40ft": 22 },
    },
    trade: {
      moq: "1 x 40ft Reefer Container (22 MT)",
      leadTime: "7-10 days",
      incoterms: ["FOB JNPT/Chennai", "CFR"],
      paymentTerms: ["LC, TT"],
      inspection: "Third-party inspection at loading",
      documents: ["Standard docs + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "20-25 days from harvest",
    storage: "Store at 10-15°C with 85-90% humidity.",
    capabilities: { privateLabel: false, monthlyCapacityMT: 1000, samples: "Not applicable" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Seasonal product with peak availability during summer months." },
    notes: "Both seeded and seedless varieties can be sourced.",
  },
  {
    id: "mango",
    name: "Mango",
    hsCode: "08045020",
    category: "Fruits",
    subCategory: "Tropical Fruits",
    images: {
      cover: "/products/fruits-mango/image (1).jpeg?height=600&width=800",
      gallery: ["/products/fruits-mango/image (2).jpeg?height=400&width=600", "/products/fruits-mango/image (3).jpeg?height=400&width=600"],
    },
    summary: "The 'King of Fruits', Indian mangoes are celebrated for their sweetness, rich flavor, and aromatic pulp. Exported fresh via air and sea.",
    specs: {
      grade: "A-Grade (e.g., Alphonso, Kesar, Banganpalli)",
      keyParameters: {
        sizeOrLength: "200g - 350g per fruit",
        defects: "Uniform size and color, free from blemishes and pests",
        purityOrActives: "Brix level > 18",
      },
      compliance: {
        marketMRLs: ["EU", "US (post-irradiation)", "Japan", "GCC"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra, Gujarat, Andhra Pradesh, Uttar Pradesh" },
    packaging: {
      options: ["3kg, 5kg Corrugated Fibreboard (CFB) boxes"],
      palletization: true,
      containerLoadability: { "20ft": 8, "40ft": 18 },
    },
    trade: {
      moq: "500 kg (By Air), 8 MT (By Sea)",
      leadTime: "3-5 days (Air), 15-20 days (Sea)",
      incoterms: ["FOB Mumbai/Chennai", "CIF/CFR"],
      paymentTerms: ["100% Advance TT for Air shipments", "LC for Sea shipments"],
      inspection: "VHT/Irradiation as per country norms, APEDA certified",
      documents: ["Standard docs + Phytosanitary Certificate", "GlobalG.A.P. certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "15-20 days under controlled temperature",
    storage: "Store at 8-12°C depending on variety.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 1000, samples: "On request" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Highly seasonal (March-July). Price varies significantly by variety." },
    notes: "Mango pulp (aseptic) is also a major export product.",
  },
  {
    id: "pomegranate",
    name: "Pomegranate",
    hsCode: "08109010",
    category: "Fruits",
    subCategory: "Exotic Fruits",
    images: {
      cover: "/products/fruits-promogranates/image (1).jpeg?height=600&width=800",
      gallery: ["/products/fruits-promogranates/image (2).jpeg?height=400&width=600", "/products/fruits-promogranates/image (3).jpeg?height=400&width=600"],
    },
    summary: "Premium quality pomegranates with a vibrant red rind and juicy, ruby-red arils. Known for their high antioxidant content.",
    specs: {
      grade: "A-Grade (e.g., Bhagwa)",
      keyParameters: {
        sizeOrLength: "180g - 400g per fruit",
        defects: "Free from cracks, sunburn, and disease",
        purityOrActives: "Sweet taste, soft seeds, Brix > 15",
      },
      compliance: {
        marketMRLs: ["EU", "UK", "GCC", "ASEAN"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra, Karnataka" },
    packaging: {
      options: ["3.5kg, 5kg CFB boxes"],
      palletization: true,
      containerLoadability: { "20ft": 9, "40ft": 20 },
    },
    trade: {
      moq: "1 x 40ft Reefer Container (20 MT)",
      leadTime: "10-15 days",
      incoterms: ["FOB JNPT/Mumbai", "CFR"],
      paymentTerms: ["LC, TT"],
      inspection: "APEDA certified packhouse",
      documents: ["Standard docs + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "60 days at 5°C",
    storage: "Store at 5-7°C with 90-95% relative humidity.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 3000, samples: "On request" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Price based on fruit count per box (e.g., 9, 10, 12 count)." },
    notes: "Also exported as fresh arils and juice concentrate.",
  },
  {
    id: "grapes",
    name: "Grapes",
    hsCode: "08061000",
    category: "Fruits",
    subCategory: "Berries",
    images: {
      cover: "/products/fruits-grapes/image (2).jpeg?height=600&width=800",
      gallery: ["/products/fruits-grapes/image (2).jpeg?height=400&width=600", "/products/fruits-grapes/image (2).jpeg?height=400&width=600"],
    },
    summary: "Fresh table grapes, known for their crisp texture and sweetness. Available in white seedless and black seedless varieties.",
    specs: {
      grade: "A-Grade (e.g., Thompson Seedless, Sonaka)",
      keyParameters: {
        sizeOrLength: "Berry size > 16mm",
        defects: "Uniform bunch size, free from decay",
        purityOrActives: "Brix > 16",
      },
      compliance: {
        marketMRLs: ["EU", "UK", "Russia", "China"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra (Nashik, Sangli)" },
    packaging: {
      options: ["5kg CFB boxes in thermocol chests", "4.5kg punnet packaging"],
      palletization: true,
      containerLoadability: { "20ft": 8, "40ft": 18 },
    },
    trade: {
      moq: "1 x 40ft Reefer Container (18 MT)",
      leadTime: "10-15 days",
      incoterms: ["FOB JNPT", "CFR"],
      paymentTerms: ["LC, TT"],
      inspection: "APEDA Grapenet traceability system compliant",
      documents: ["Standard docs + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "45-70 days under controlled atmosphere",
    storage: "Store at 0-1°C with 90-95% humidity.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 5000, samples: "On request" },
    pricing: { currency: "USD", basis: ["FOB", "CFR"], priceOnRequest: true, notes: "Strict MRL compliance required for EU market." },
    notes: "Main season is from January to April.",
  },
  {
    id: "chickpeas",
    name: "Chickpeas (Kabuli Chana)",
    hsCode: "07132000",
    category: "Pulses",
    subCategory: "Beans",
    images: {
      cover: "/products/pulses-cabulichana/image (2).jpeg?height=600&width=800",
      gallery: ["/products/pulses-cabulichana/image (1).jpeg?height=400&width=600", "/products/pulses-cabulichana/image (3).jpeg?height=400&width=600"],
    },
    summary: "High-quality Kabuli chickpeas, known for their large size, creamy texture, and nutty flavor. A versatile ingredient in global cuisines.",
    specs: {
      grade: "A-Grade, various calibers",
      keyParameters: {
        moisture: "12% max",
        sizeOrLength: "44/46, 58/60, 75/80 counts per ounce",
        defects: "Broken/Split < 2%",
        foreignMatter: "< 0.5%",
      },
      compliance: {
        marketMRLs: ["GCC", "Europe", "North America"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Madhya Pradesh, Maharashtra, Rajasthan" },
    packaging: {
      options: ["25kg, 50kg PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 24, "40ft": 26 },
    },
    trade: {
      moq: "1 x 20ft Container (24 MT)",
      leadTime: "15-20 days",
      incoterms: ["FOB JNPT/Mundra", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "SGS or similar at loading port",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in a cool, dry, and clean place.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 1500, samples: "Available (500g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Price is dependent on caliber/size of the chickpeas." },
    notes: "Also known as Garbanzo beans.",
  },
  {
    id: "red-lentils",
    name: "Red Lentils (Masoor)",
    hsCode: "07134000",
    category: "Pulses",
    subCategory: "Lentils",
    images: {
      cover: "/products/pulses-masoor/image (1).jpeg?height=600&width=800",
      gallery: ["/products/pulses-masoor/image (2).jpeg?height=400&width=600", "/products/pulses-masoor/image (3).jpeg?height=400&width=600"],
    },
    summary: "Whole and split red lentils, a staple protein source. Cooks quickly and is used extensively in soups, stews, and curries.",
    specs: {
      grade: "FAQ",
      keyParameters: {
        moisture: "13% max",
        purityOrActives: "Purity 98% min",
        defects: "Damaged/Weevilled < 2%",
        foreignMatter: "< 1%",
      },
      compliance: {
        marketMRLs: ["South Asia", "Middle East", "North Africa"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Uttar Pradesh, Madhya Pradesh, West Bengal" },
    packaging: {
      options: ["25kg, 50kg PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 24, "40ft": 26 },
    },
    trade: {
      moq: "24 MT",
      leadTime: "20-25 days",
      incoterms: ["FOB Mundra/Kolkata", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "Third-party inspection available",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in a dry, ventilated warehouse.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 2000, samples: "Available (500g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Available as football split and whole lentils." },
    notes: "A key source of plant-based protein.",
  },
    {
    id: "pigeon-peas",
    name: "Pigeon Peas (Toor Dal)",
    hsCode: "07136000",
    category: "Pulses",
    subCategory: "Peas",
    images: {
      cover: "/products/pulses-turdal/image (1).jpeg?height=600&width=800",
      gallery: ["/products/pulses-turdal/image (2).jpeg?height=400&width=600", "/products/pulses-turdal/image (3).jpeg?height=400&width=600"],
    },
    summary: "A staple pulse in South Asia, pigeon peas (or Toor Dal) are a primary source of protein. Available in whole, split-husked, and split-skinned forms.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        moisture: "12% max",
        purityOrActives: "Purity 98.5% min",
        defects: "Damaged/Broken < 2%",
        foreignMatter: "< 1%",
      },
      compliance: {
        marketMRLs: ["GCC", "US", "UK", "Canada", "ASEAN"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra, Karnataka, Madhya Pradesh" },
    packaging: {
      options: ["25kg, 50kg PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 24, "40ft": 26 },
    },
    trade: {
      moq: "1 x 20ft Container (24 MT)",
      leadTime: "15-20 days",
      incoterms: ["FOB JNPT/Mundra", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "SGS or similar at loading port",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in a cool, dry, and clean place.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 1000, samples: "Available (500g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Split-skinned (Toor Dal) is the most commonly traded form." },
    notes: "Also known as Arhar dal.",
  },
  {
    id: "mung-beans",
    name: "Mung Beans (Green Gram)",
    hsCode: "07133100",
    category: "Pulses",
    subCategory: "Beans",
    images: {
      cover: "/products/pulses-mongdal/image (1).jpeg?height=600&width=800",
      gallery: ["/products/pulses-mongdal/image (2).jpeg?height=400&width=600", "/products/pulses-mongdal/image (3).jpeg?height=400&width=600"],
    },
    summary: "Small, green beans that are a nutritious staple in Asian cuisine. Used whole for sprouting, or split for making dal and desserts.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        moisture: "12% max",
        sizeOrLength: "2.8mm - 3.5mm",
        defects: "Foreign Matter < 1%",
        purityOrActives: "Purity 99% min",
      },
      compliance: {
        marketMRLs: ["Global"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Rajasthan, Maharashtra, Andhra Pradesh" },
    packaging: {
      options: ["25kg, 50kg PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 24, "40ft": 26 },
    },
    trade: {
      moq: "24 MT",
      leadTime: "15-20 days",
      incoterms: ["FOB Mundra", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "Third-party inspection available",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in a dry, ventilated warehouse.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 1500, samples: "Available (500g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Shiny green variety is preferred for export." },
    notes: "High demand for sprouting purposes in East and Southeast Asia.",
  },
  {
    id: "kidney-beans",
    name: "Kidney Beans (Rajma)",
    hsCode: "07133300",
    category: "Pulses",
    subCategory: "Beans",
    images: {
      cover: "/products/pulses-rajma/image (2).jpeg?height=600&width=800",
      gallery: ["/products/pulses-rajma/image (1).jpeg?height=400&width=600", "/products/pulses-rajma/image (3).jpeg?height=400&width=600"],
    },
    summary: "Premium quality dried kidney beans, known for their distinctive shape and deep red color. A nutritious and popular ingredient in cuisines worldwide.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        moisture: "13% max",
        purityOrActives: "Purity 99% min",
        defects: "Damaged/Broken < 2%",
        foreignMatter: "< 0.5%",
      },
      compliance: {
        marketMRLs: ["Global"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra, Jammu & Kashmir, Himachal Pradesh" },
    packaging: {
      options: ["25kg, 50kg PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 24, "40ft": 26 },
    },
    trade: {
      moq: "1 x 20ft Container (24 MT)",
      leadTime: "15-20 days",
      incoterms: ["FOB JNPT/Mundra", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "SGS or similar at loading port",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in a cool, dry, and clean place.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 500, samples: "Available (500g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Dark red kidney beans are the most common export variety." },
    notes: "A rich source of protein, fiber, and essential minerals.",
  },
  {
    id: "black-gram",
    name: "Black Gram (Urad Dal)",
    hsCode: "07133990",
    category: "Pulses",
    subCategory: "Beans",
    images: {
      cover: "/products/pulses-uraddal/image (1).jpeg?height=600&width=800",
      gallery: ["/products/pulses-uraddal/image (1).jpeg?height=400&width=600", "/products/pulses-uraddal/image (1).jpeg?height=400&width=600"],
    },
    summary: "Black gram, a highly nutritious pulse, is a cornerstone of Indian cuisine. Exported as whole, split, and split-skinned (Urad Dal).",
    specs: {
      grade: "FAQ (Fair Average Quality)",
      keyParameters: {
        moisture: "12% max",
        purityOrActives: "Purity 98% min",
        defects: "Damaged/Weevilled < 2%",
        foreignMatter: "< 1.5%",
      },
      compliance: {
        marketMRLs: ["Global"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra, Andhra Pradesh, Uttar Pradesh" },
    packaging: {
      options: ["25kg, 50kg PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 24, "40ft": 26 },
    },
    trade: {
      moq: "24 MT",
      leadTime: "20-25 days",
      incoterms: ["FOB JNPT/Chennai", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "Third-party inspection available",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in a dry, ventilated warehouse.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 800, samples: "Available (500g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Urad Dal is used in batters for famous dishes like Dosa and Idli." },
    notes: "Available in both polished and unpolished forms.",
  },

  {
    id: "basmati-rice",
    name: "Basmati Rice",
    hsCode: "10063020",
    category: "Grains",
    subCategory: "Rice",
    images: {
      cover: "/products/grains-rice/image (1).jpeg?height=600&width=800",
      gallery: ["/products/grains-rice/image (2).jpeg?height=400&width=600", "/products/grains-rice/image (3).jpeg?height=400&width=600"],
    },
    summary: "Premium long-grain aromatic rice from India, known for its distinct fragrance and fluffy texture upon cooking. Ideal for global cuisines.",
    specs: {
      grade: "A-Grade, Long Grain",
      keyParameters: {
        moisture: "13% max",
        purityOrActives: "Purity 95% min",
        sizeOrLength: "Average Grain Length 8.30 mm",
        defects: "Broken < 2%",
        foreignMatter: "< 0.5%",
      },
      compliance: {
        marketMRLs: ["EU", "US", "GCC", "ASEAN"],
        gmo: "Non-GMO",
        allergens: "Gluten-free",
      },
    },
    origin: { country: "India", region: "Punjab, Haryana, Uttar Pradesh" },
    packaging: {
      options: ["1kg, 5kg, 10kg PP/Non-woven bags", "25kg, 50kg PP/Jute bags", "Custom packaging"],
      palletization: true,
      containerLoadability: { "20ft": 25, "40ft": 27 },
    },
    trade: {
      moq: "1 x 20ft Container (approx. 25 MT)",
      leadTime: "15-20 days from payment confirmation",
      incoterms: ["FOB Mundra/JNPT", "CIF any port"],
      paymentTerms: ["100% Irrevocable LC at sight", "30% TT Advance, 70% against Scanned B/L"],
      inspection: "SGS, Bureau Veritas, or any third party at buyer's cost",
      documents: ["Commercial Invoice", "Packing List", "Bill of Lading", "Certificate of Origin", "Phytosanitary Certificate", "Fumigation Certificate", "Certificate of Analysis"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in a cool, dry place away from direct sunlight and pests.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 1000, samples: "Available (500g), 5-7 days lead time" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Price depends on grain length, broken %, and packaging." },
    notes: "Available in Sella (Parboiled), Steam, and Raw/White varieties.",
  },
  {
    id: "durum-wheat",
    name: "Durum Wheat",
    hsCode: "10011900",
    category: "Grains",
    subCategory: "Wheat",
    images: {
      cover: "/products/grains-wheat/image (2).jpeg?height=600&width=800",
      gallery: ["/products/grains-wheat/image (1).jpeg?height=400&width=600", "/products/grains-wheat/image (3).jpeg?height=400&width=600"],
    },
    summary: "High-quality hard durum wheat, rich in protein and gluten. Primarily used for making pasta, couscous, and semolina.",
    specs: {
      grade: "Milling Grade 1",
      keyParameters: {
        moisture: "12% max",
        purityOrActives: "Protein 12.5% min",
        defects: "Damaged Kernels < 2%",
        foreignMatter: "< 1%",
        hectoliterWeight: "78 kg/hl min",
      },
      compliance: {
        marketMRLs: ["EU", "North Africa", "Middle East"],
        gmo: "Non-GMO",
        allergens: "Contains Gluten",
      },
    },
    origin: { country: "India", region: "Madhya Pradesh, Gujarat, Punjab" },
    packaging: {
      options: ["50kg PP bags", "Bulk in container"],
      palletization: true,
      containerLoadability: { "20ft": 26, "40ft": 28 },
    },
    trade: {
      moq: "50 MT (2 x 20ft Containers)",
      leadTime: "20-25 days",
      incoterms: ["FOB Kandla/Mundra", "CIF"],
      paymentTerms: ["LC at sight", "TT"],
      inspection: "Third-party inspection at loading port",
      documents: ["Commercial Invoice", "Packing List", "Bill of Lading", "Certificate of Origin", "Phytosanitary Certificate", "Certificate of Analysis"],
    },
    certifications: ["APEDA"],
    shelfLife: "18 months",
    storage: "Store in dry, well-ventilated silos or warehouses.",
    capabilities: { privateLabel: false, monthlyCapacityMT: 5000, samples: "Available (1kg)" },
    pricing: { currency: "USD", basis: ["FOB", "CNF"], priceOnRequest: true, notes: "Pricing is subject to global commodity market fluctuations." },
    notes: "Also known as Pasta Wheat or Macaroni Wheat.",
  },
  {
    id: "sorghum",
    name: "Sorghum (Jowar)",
    hsCode: "10079000",
    category: "Grains",
    subCategory: "Major Millets",
    images: {
      cover: "/products/grains-jowar/image (1).jpeg?height=600&width=800",
      gallery: ["/products/grains-jowar/image (2).jpeg?height=400&width=600", "/products/grains-jowar/image (3).jpeg?height=400&width=600"],
    },
    summary: "A versatile and drought-resistant gluten-free millet, used as a staple food, animal fodder, and for ethanol production.",
    specs: {
      grade: "FAQ (Fair Average Quality)",
      keyParameters: {
        moisture: "12% max",
        purityOrActives: "Purity 98% min",
        defects: "Damaged grains < 2%",
        foreignMatter: "< 2%",
      },
      compliance: {
        marketMRLs: ["Global"],
        gmo: "Non-GMO",
        allergens: "Gluten-free",
      },
    },
    origin: { country: "India", region: "Maharashtra, Karnataka, Rajasthan" },
    packaging: {
      options: ["25kg, 50kg PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 24, "40ft": 26 },
    },
    trade: {
      moq: "1 x 20ft Container",
      leadTime: "2-3 weeks",
      incoterms: ["FOB JNPT/Mundra", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "Third-party inspection available",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "18 months",
    storage: "Store in clean, dry conditions.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 2000, samples: "Available (1kg)" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Both white (food) and red (feed) varieties available." },
    notes: "A staple crop in semi-arid regions, gaining popularity as a health food.",
  },
  {
    id: "pearl-millet",
    name: "Pearl Millet (Bajra)",
    hsCode: "10082920",
    category: "Grains",
    subCategory: "Major Millets",
    images: {
      cover: "/products/grains-bajra/image (1).jpeg?height=600&width=800",
      gallery: ["/products/grains-bajra/image (2).jpeg?height=400&width=600", "/products/grains-bajra/image (3).jpeg?height=400&width=600"],
    },
    summary: "A nutrient-rich, gluten-free millet with high iron content, widely consumed in Africa and Asia. Excellent for flatbreads and porridge.",
    specs: {
      grade: "FAQ",
      keyParameters: {
        moisture: "12% max",
        purityOrActives: "Purity 98%",
        defects: "Damaged grains < 2%",
        foreignMatter: "< 2%",
      },
      compliance: {
        marketMRLs: ["Global"],
        gmo: "Non-GMO",
        allergens: "Gluten-free",
      },
    },
    origin: { country: "India", region: "Rajasthan, Uttar Pradesh, Gujarat" },
    packaging: {
      options: ["25kg, 50kg PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 25, "40ft": 27 },
    },
    trade: {
      moq: "25 MT",
      leadTime: "3-4 weeks",
      incoterms: ["FOB Mundra", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "Available at buyer's request",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "12 months",
    storage: "Store in cool, dry place.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 3000, samples: "Available" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Best prices during harvest season (Sept-Nov)." },
    notes: "Highly resilient crop, suitable for arid farming conditions.",
  },
  {
    id: "turmeric-fingers",
    name: "Turmeric Fingers",
    hsCode: "09103020",
    category: "Spices",
    subCategory: "Whole Spices",
    images: {
      cover: "/products/spices-turmeric/image (1).jpeg?height=600&width=800",
      gallery: ["/products/spices-turmeric/image (2).jpeg?height=400&width=600", "/products/spices-turmeric/image (3).jpeg?height=400&width=600"],
    },
    summary: "Dried rhizomes of the turmeric plant, prized for their high curcumin content, vibrant color, and medicinal properties.",
    specs: {
      grade: "FAQ / Polished",
      keyParameters: {
        moisture: "12% max",
        purityOrActives: "Curcumin 2% to 5% available",
        defects: "Bulbs < 2%",
        foreignMatter: "< 1%",
      },
      compliance: {
        marketMRLs: ["EU", "US", "Japan"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Tamil Nadu (Erode), Andhra Pradesh, Maharashtra" },
    packaging: {
      options: ["25kg, 50kg Jute/PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 18, "40ft": 26 },
    },
    trade: {
      moq: "10 MT",
      leadTime: "15-20 days",
      incoterms: ["FOB Chennai/Mumbai", "CIF"],
      paymentTerms: ["LC, TT, CAD"],
      inspection: "SGS inspection for quality and weight",
      documents: ["All standard docs + Spices Board Certificate", "Certificate of Analysis (for Curcumin)"],
    },
    certifications: ["APEDA"],
    shelfLife: "36 months",
    storage: "Store in a dry place away from direct heat and light.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 500, samples: "Available (250g)" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Price is directly correlated with curcumin percentage." },
    notes: "Also available in powder form. Steam sterilization option available.",
  },
  {
    id: "black-pepper",
    name: "Black Pepper",
    hsCode: "09041130",
    category: "Spices",
    subCategory: "Whole Spices",
    images: {
      cover: "/products/spices-pepper/image (1).jpeg?height=600&width=800",
      gallery: ["/products/spices-pepper/image (2).jpeg?height=400&width=600", "/products/spices-pepper/image (3).jpeg?height=400&width=600"],
    },
    summary: "The 'King of Spices', whole dried berries of Piper nigrum. Known for its pungent flavor and aroma derived from piperine.",
    specs: {
      grade: "Malabar Garbled / 550 G/L",
      keyParameters: {
        moisture: "12.5% max",
        purityOrActives: "Piperine 4% min",
        defects: "Light berries < 3%",
        foreignMatter: "< 0.5%",
      },
      compliance: {
        marketMRLs: ["EU", "US", "Japan", "GCC"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Kerala, Karnataka" },
    packaging: {
      options: ["25kg, 50kg Jute/PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 15, "40ft": 25 },
    },
    trade: {
      moq: "5 MT",
      leadTime: "2-3 weeks",
      incoterms: ["FOB Cochin", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "SGS/Intertek at loading port",
      documents: ["Standard export docs + Spices Board Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "36 months",
    storage: "Store in airtight containers in a cool, dark, dry place.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 200, samples: "Available (250g)" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Price varies by density (G/L - Grams per Litre) and origin." },
    notes: "Organic and steam-sterilized variants available.",
  },
  {
    id: "dry-red-chili",
    name: "Dry Red Chili",
    hsCode: "09042110",
    category: "Spices",
    subCategory: "Whole Spices",
    images: {
      cover: "/products/spices-redchilli/image (1).jpeg?height=600&width=800",
      gallery: ["/products/spices-redchilli/image (2).jpeg?height=400&width=600", "/products/spices-redchilli/image (3).jpeg?height=400&width=600"],
    },
    summary: "Dried pods of chili peppers, used whole or ground to add pungency and color to dishes. Available in various heat levels and sizes.",
    specs: {
      grade: "Teja / Byadgi / Sannam",
      keyParameters: {
        moisture: "12% max",
        purityOrActives: "Heat: 15,000 to 80,000 SHU",
        defects: "Broken/Loose seeds < 5%",
        foreignMatter: "< 2%",
        contaminants: "Aflatoxin < 10 ppb, Sudan Dye free",
      },
      compliance: {
        marketMRLs: ["EU", "US", "Mexico", "ASEAN"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Andhra Pradesh (Guntur), Telangana, Karnataka" },
    packaging: {
      options: ["5kg, 10kg, 25kg Jute/PP bags"],
      palletization: false,
      containerLoadability: { "20ft": 6.5, "40ft": 14 },
    },
    trade: {
      moq: "6.5 MT (1 x 20ft Container)",
      leadTime: "15-20 days",
      incoterms: ["FOB Chennai/Tuticorin", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "SGS inspection",
      documents: ["Standard export docs + Spices Board Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in a well-ventilated, cool, dry place.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 1000, samples: "Available" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Price depends on variety, heat (SHU), color (ASTA), and season." },
    notes: "Available with stem and stemless. Powder and flakes also available.",
  },
  {
    id: "fresh-onion",
    name: "Fresh Onion",
    hsCode: "07031010",
    category: "Vegetables",
    subCategory: "Bulb Vegetables",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "High-quality fresh onions, a staple ingredient worldwide. Known for their pungency and flavor. Sourced from prime agricultural regions.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        sizeOrLength: "45-60mm, 50-70mm, 60-80mm",
        defects: "Free from soil, pests, rot, and sprouting",
        purityOrActives: "Uniform color and firm texture",
      },
      compliance: {
        marketMRLs: ["GCC", "Sri Lanka", "Malaysia", "Europe"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra (Nashik), Karnataka, Gujarat" },
    packaging: {
      options: ["5kg, 10kg, 25kg, 50kg Mesh/Leno bags"],
      palletization: false,
      containerLoadability: { "20ft": 13, "40ft": 29 },
    },
    trade: {
      moq: "1 x 40ft Reefer Container (approx. 29 MT)",
      leadTime: "7-10 days",
      incoterms: ["FOB JNPT/Mundra", "CFR"],
      paymentTerms: ["100% Advance TT", "LC at sight"],
      inspection: "APEDA certified packhouse inspection",
      documents: ["Standard export documents + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "30-45 days under controlled conditions",
    storage: "Store at 0-2°C with good ventilation.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 2500, samples: "Not applicable" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Prices are highly seasonal and market-dependent." },
    notes: "Red, Pink, and Yellow varieties are available.",
  },
  {
    id: "fresh-potato",
    name: "Fresh Potato",
    hsCode: "07019000",
    category: "Vegetables",
    subCategory: "Tuber Vegetables",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "Versatile and nutritious fresh potatoes, suitable for table consumption, processing into fries, and chips. Washed and graded for export.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        sizeOrLength: "50g to 250g per piece",
        defects: "Free from greening, cuts, pests, and rot",
        purityOrActives: "Smooth skin, firm flesh",
      },
      compliance: {
        marketMRLs: ["GCC", "Russia", "ASEAN"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Uttar Pradesh, West Bengal, Gujarat" },
    packaging: {
      options: ["10kg, 25kg, 50kg Jute/Mesh bags"],
      palletization: false,
      containerLoadability: { "20ft": 13, "40ft": 29 },
    },
    trade: {
      moq: "1 x 40ft Reefer Container (29 MT)",
      leadTime: "10-15 days",
      incoterms: ["FOB Mundra/Kolkata", "CFR"],
      paymentTerms: ["Advance TT, LC"],
      inspection: "Third-party inspection",
      documents: ["Standard export documents + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "2-3 months under optimal conditions",
    storage: "Store in a dark, cool (4-8°C), well-ventilated area.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 4000, samples: "Not applicable" },
    pricing: { currency: "USD", basis: ["FOB", "CFR"], priceOnRequest: true, notes: "Processing and table varieties have different pricing." },
    notes: "Multiple varieties available, including Chipsona (processing) and Jyoti (table).",
  },
  {
    id: "fresh-ginger",
    name: "Fresh Ginger",
    hsCode: "09101110",
    category: "Vegetables",
    subCategory: "Rhizomes",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "Aromatic and pungent fresh ginger, washed and treated for export. Widely used as a spice in cooking and for its medicinal benefits.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        sizeOrLength: "Weight 100g and above per rhizome",
        defects: "Clean, no pests, no rot, firm",
        purityOrActives: "Well-formed, pungent aroma",
      },
      compliance: {
        marketMRLs: ["EU", "US", "GCC"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Karnataka, Kerala, Assam" },
    packaging: {
      options: ["5kg, 10kg, 13.6kg (30lbs) CFB boxes"],
      palletization: true,
      containerLoadability: { "20ft": 11, "40ft": 24 },
    },
    trade: {
      moq: "1 x 40ft Reefer Container (24 MT)",
      leadTime: "10-12 days",
      incoterms: ["FOB Cochin/JNPT", "CFR"],
      paymentTerms: ["Advance TT, LC"],
      inspection: "APEDA packhouse standards",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "45-60 days at 12-14°C",
    storage: "Store at 12-14°C with 65% relative humidity.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 500, samples: "Not applicable" },
    pricing: { currency: "USD", basis: ["FOB", "CFR"], priceOnRequest: true, notes: "Prices peak just before the new harvest." },
    notes: "Available as fresh, and also processed into dry ginger, powder, and oil.",
  },
  {
    id: "peanuts",
    name: "Peanuts (Groundnuts)",
    hsCode: "12024210",
    category: "Oilseeds",
    subCategory: "Nuts",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "High-quality peanut kernels, a rich source of oil and protein. Used for oil extraction, snacking, and food manufacturing.",
    specs: {
      grade: "Java / Bold type",
      keyParameters: {
        moisture: "8% max",
        sizeOrLength: "40/50, 50/60, 60/70, 80/90 counts per ounce",
        defects: "Imperfect kernels < 3%",
        contaminants: "Aflatoxin < 10 ppb (as per destination country)",
      },
      compliance: {
        marketMRLs: ["EU", "ASEAN", "China"],
        gmo: "Non-GMO",
        allergens: "Contains Peanuts",
      },
    },
    origin: { country: "India", region: "Gujarat, Rajasthan, Andhra Pradesh" },
    packaging: {
      options: ["25kg, 50kg Jute/PP bags", "25kg Vacuum bags"],
      palletization: true,
      containerLoadability: { "20ft": 19, "40ft": 26 },
    },
    trade: {
      moq: "19 MT",
      leadTime: "15-20 days",
      incoterms: ["FOB Mundra", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "SGS for Aflatoxin and quality check",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "12 months",
    storage: "Store in a cool, dry place below 20°C.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 4000, samples: "Available (500g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Price varies with kernel size (counts per ounce)." },
    notes: "Strict Aflatoxin control is critical for EU exports.",
  },
  {
    id: "sesame-seeds",
    name: "Sesame Seeds",
    hsCode: "12074090",
    category: "Oilseeds",
    subCategory: "Seeds",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "Natural and hulled sesame seeds, known for their high oil content and nutty flavor. Used in baking, confectionery, and for tahini production.",
    specs: {
      grade: "99/1/1, 99.95% Purity",
      keyParameters: {
        moisture: "6% max",
        purityOrActives: "Purity up to 99.98%",
        sizeOrLength: "Oil content 48% min",
        foreignMatter: "< 0.05%",
      },
      compliance: {
        marketMRLs: ["Global"],
        gmo: "Non-GMO",
        allergens: "Contains Sesame",
      },
    },
    origin: { country: "India", region: "Gujarat, West Bengal, Rajasthan" },
    packaging: {
      options: ["25kg, 50kg PP/Paper bags"],
      palletization: true,
      containerLoadability: { "20ft": 19, "40ft": 26 },
    },
    trade: {
      moq: "19 MT",
      leadTime: "15-20 days",
      incoterms: ["FOB Mundra/Kolkata", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "Third-party inspection",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in cool, dry conditions.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 2000, samples: "Available (250g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Hulled sesame commands a premium over natural." },
    notes: "Available in natural white, black, and hulled varieties.",
  },
  {
    id: "yellow-maize",
    name: "Yellow Maize (Corn)",
    hsCode: "10059000",
    category: "Grains",
    subCategory: "Coarse Grains",
    images: {
      cover: "/products/grains-maize/image (3).jpeg?height=600&width=800",
      gallery: ["/products/grains-maize/image (1).jpeg?height=400&width=600", "/products/grains-maize/image (2).jpeg?height=400&width=600"],
    },
    summary: "High-quality yellow maize, primarily used for animal feed (poultry, cattle) and industrial applications like starch production.",
    specs: {
      grade: "Feed Grade / Food Grade",
      keyParameters: {
        moisture: "14% max",
        purityOrActives: "Protein 8% min",
        defects: "Broken kernels < 3%",
        foreignMatter: "< 1.5%",
        contaminants: "Aflatoxin < 20 ppb",
      },
      compliance: {
        marketMRLs: ["ASEAN", "GCC", "Africa"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Karnataka, Maharashtra, Bihar" },
    packaging: {
      options: ["50kg PP bags", "Bulk vessel"],
      palletization: true,
      containerLoadability: { "20ft": 26, "40ft": 28 },
    },
    trade: {
      moq: "100 MT",
      leadTime: "15-25 days",
      incoterms: ["FOB Kakinada/Chennai", "CIF"],
      paymentTerms: ["LC at sight", "TT"],
      inspection: "SGS/Intertek at origin",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in a cool, dry, and pest-free environment.",
    capabilities: { privateLabel: false, monthlyCapacityMT: 10000, samples: "Available upon request" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Prices are highly volatile and based on harvest season." },
    notes: "Human consumption grade is also available with stricter quality parameters.",
  },
  {
    id: "okra-ladies-finger",
    name: "Okra (Lady's Finger)",
    hsCode: "07099920",
    category: "Vegetables",
    subCategory: "Fruit Vegetables",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "Fresh, tender green okra pods, carefully selected and packed for export. A popular vegetable in Middle Eastern, Asian, and African cuisines.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        sizeOrLength: "7-10 cm in length",
        defects: "Free from pests, damage, and blemishes. Fresh green color.",
        purityOrActives: "Tender and crisp texture",
      },
      compliance: {
        marketMRLs: ["GCC", "Europe", "UK"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Gujarat, Maharashtra, Andhra Pradesh" },
    packaging: {
      options: ["5kg thermocol boxes", "5kg corrugated fibreboard boxes"],
      palletization: true,
      containerLoadability: { "20ft": 6, "40ft": 14 },
    },
    trade: {
      moq: "1000 kg (By Air)",
      leadTime: "3-5 days",
      incoterms: ["FOB Mumbai/Ahmedabad", "CFR"],
      paymentTerms: ["100% Advance TT for air shipments"],
      inspection: "APEDA certified packhouse inspection",
      documents: ["Standard export documents + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "7-10 days under controlled temperature",
    storage: "Store at 7-10°C with 90-95% relative humidity.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 500, samples: "Not applicable" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Primarily exported via air cargo due to short shelf life." },
    notes: "Harvested and packed quickly to maintain freshness.",
  },
  {
    id: "fresh-tomato",
    name: "Fresh Tomato",
    hsCode: "07020000",
    category: "Vegetables",
    subCategory: "Fruit Vegetables",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "Firm, vibrant red tomatoes, cultivated for their rich flavor and long shelf life. Suitable for fresh consumption and processing.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        sizeOrLength: "50mm-70mm diameter",
        defects: "Free from cracks, bruising, and pests. Uniform shape.",
        purityOrActives: "Firm texture, Brix > 4.5",
      },
      compliance: {
        marketMRLs: ["GCC", "Maldives", "Bangladesh"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Maharashtra, Karnataka, Andhra Pradesh" },
    packaging: {
      options: ["7kg, 10kg CFB boxes with ventilation"],
      palletization: true,
      containerLoadability: { "20ft": 10, "40ft": 22 },
    },
    trade: {
      moq: "1 x 40ft Reefer Container (22 MT)",
      leadTime: "7-10 days",
      incoterms: ["FOB JNPT/Mundra", "CFR"],
      paymentTerms: ["LC, Advance TT"],
      inspection: "Third-party inspection at loading",
      documents: ["Standard export documents + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "20-25 days under optimal conditions",
    storage: "Store at 10-13°C with 85-95% humidity.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 1000, samples: "Not applicable" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Hybrid varieties with longer shelf life are used for export." },
    notes: "Available year-round with seasonal price variations.",
  },
  {
    id: "soybean",
    name: "Soybean",
    hsCode: "12019000",
    category: "Oilseeds",
    subCategory: "Beans",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "High-protein soybeans, a versatile crop used for producing oil, animal feed (soybean meal), and a variety of food products like tofu and soy milk.",
    specs: {
      grade: "Grade 1 / FAQ",
      keyParameters: {
        moisture: "12% max",
        purityOrActives: "Protein 38% min, Oil 18% min",
        defects: "Damaged/Split kernels < 3%",
        foreignMatter: "< 1%",
      },
      compliance: {
        marketMRLs: ["ASEAN", "South Asia"],
        gmo: "Non-GMO",
        allergens: "Contains Soy",
      },
    },
    origin: { country: "India", region: "Madhya Pradesh, Maharashtra, Rajasthan" },
    packaging: {
      options: ["50kg PP bags", "Bulk in container"],
      palletization: true,
      containerLoadability: { "20ft": 25, "40ft": 27 },
    },
    trade: {
      moq: "1 x 20ft Container (25 MT)",
      leadTime: "20-25 days",
      incoterms: ["FOB Mundra/Kandla", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "SGS or similar at loading port",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "18 months",
    storage: "Store in a cool, dry place to prevent mold.",
    capabilities: { privateLabel: false, monthlyCapacityMT: 10000, samples: "Available (1kg)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Non-GMO soybean meal is a major value-added export." },
    notes: "Indian soybeans are valued for being Non-GMO by default.",
  },
  {
    id: "mustard-seeds",
    name: "Mustard Seeds",
    hsCode: "12075090",
    category: "Oilseeds",
    subCategory: "Seeds",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "Pungent and flavorful mustard seeds, used as a spice in cooking, for oil extraction, and in the production of mustard paste.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        moisture: "8% max",
        purityOrActives: "Purity 99% min, Oil 40% min",
        defects: "Damaged seeds < 2%",
        foreignMatter: "< 1%",
      },
      compliance: {
        marketMRLs: ["Global"],
        gmo: "Non-GMO",
        allergens: "Contains Mustard",
      },
    },
    origin: { country: "India", region: "Rajasthan, Haryana, Uttar Pradesh" },
    packaging: {
      options: ["25kg, 50kg PP/Jute bags"],
      palletization: true,
      containerLoadability: { "20ft": 22, "40ft": 26 },
    },
    trade: {
      moq: "22 MT",
      leadTime: "15-20 days",
      incoterms: ["FOB Mundra", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "Third-party inspection",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "24 months",
    storage: "Store in cool, dry conditions away from sunlight.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 500, samples: "Available (250g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Price varies between yellow, black, and brown varieties." },
    notes: "Both yellow and black mustard seeds are available.",
  },
  {
    id: "indian-barley",
    name: "Indian Barley (Jau)",
    hsCode: "10039000",
    category: "Grains",
    subCategory: "Coarse Grains",
    images: {
      cover: "/products/grains-jau/image (1).jpeg?height=600&width=800",
      gallery: ["/products/grains-jau/image (2).jpeg?height=400&width=600", "/products/grains-jau/image (3).jpeg?height=400&width=600"],
    },
    summary: "High-quality Indian barley, used globally for malting, animal feed, and as a nutritious food grain. Rich in fiber and essential minerals.",
    specs: {
      grade: "Feed Grade / Malt Grade",
      keyParameters: {
        moisture: "12% max",
        purityOrActives: "Protein 10% min",
        defects: "Foreign Matter < 2%",
        hectoliterWeight: "65 kg/hl min",
      },
      compliance: {
        marketMRLs: ["GCC", "Southeast Asia"],
        gmo: "Non-GMO",
        allergens: "Contains Gluten",
      },
    },
    origin: { country: "India", region: "Rajasthan, Uttar Pradesh, Madhya Pradesh" },
    packaging: {
      options: ["50kg PP bags", "Bulk in container"],
      palletization: true,
      containerLoadability: { "20ft": 25, "40ft": 27 },
    },
    trade: {
      moq: "1 x 20ft Container (25 MT)",
      leadTime: "20-25 days",
      incoterms: ["FOB Mundra/Kandla", "CIF"],
      paymentTerms: ["LC at sight", "TT"],
      inspection: "Third-party inspection at loading port",
      documents: ["Commercial Invoice", "Packing List", "Bill of Lading", "Certificate of Origin", "Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "18 months",
    storage: "Store in a cool, dry, and well-ventilated area.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 5000, samples: "Available (1kg)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Price differs for feed grade versus higher quality malt grade." },
    notes: "A key ingredient for the brewing and distilling industry.",
  },
  {
    id: "green-chili",
    name: "Green Chili",
    hsCode: "07096010",
    category: "Vegetables",
    subCategory: "Fruit Vegetables",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "Fresh and pungent green chilies, a staple ingredient for adding heat and flavor to cuisines worldwide. Carefully packed to retain freshness.",
    specs: {
      grade: "A-Grade (G4)",
      keyParameters: {
        sizeOrLength: "5-7 cm in length",
        defects: "Free from pests, damage, and rot. Uniform green color.",
        purityOrActives: "High pungency (capsaicin content)",
      },
      compliance: {
        marketMRLs: ["GCC", "UK", "Europe"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Andhra Pradesh, Maharashtra, Karnataka" },
    packaging: {
      options: ["3.5kg / 4kg net weight CFB boxes"],
      palletization: true,
      containerLoadability: { "20ft": 7, "40ft": 16 },
    },
    trade: {
      moq: "500 kg (By Air)",
      leadTime: "3-4 days",
      incoterms: ["FOB Mumbai/Bangalore/Chennai", "CFR"],
      paymentTerms: ["100% Advance TT for air shipments"],
      inspection: "APEDA certified packhouse inspection",
      documents: ["Standard export documents + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "10-14 days under controlled temperature",
    storage: "Store at 8-10°C.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 400, samples: "Not applicable" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "Exported year-round, primarily by air cargo." },
    notes: "Various levels of pungency are available based on the chili variety.",
  },
  {
    id: "drumstick-moringa",
    name: "Drumstick (Moringa)",
    hsCode: "07099990",
    category: "Vegetables",
    subCategory: "Pod Vegetables",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "Fresh, long, and tender drumstick pods (Moringa), highly valued for their nutritional content and use in traditional dishes and soups.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        sizeOrLength: "45-60 cm in length",
        defects: "Tender, green, and free from blemishes or over-maturity.",
        purityOrActives: "Good flavor and firm texture.",
      },
      compliance: {
        marketMRLs: ["GCC", "Canada", "UK"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Tamil Nadu, Andhra Pradesh, Maharashtra" },
    packaging: {
      options: ["6kg net weight CFB boxes"],
      palletization: true,
      containerLoadability: { "20ft": 6, "40ft": 14 },
    },
    trade: {
      moq: "500 kg (By Air)",
      leadTime: "3-5 days",
      incoterms: ["FOB Chennai/Mumbai", "CFR"],
      paymentTerms: ["100% Advance TT"],
      inspection: "Packhouse level inspection",
      documents: ["Standard export documents + Phytosanitary Certificate"],
    },
    certifications: ["APEDA"],
    shelfLife: "8-12 days under refrigeration",
    storage: "Store at 8-10°C.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 200, samples: "Not applicable" },
    pricing: { currency: "USD", basis: ["FOB"], priceOnRequest: true, notes: "A niche but consistent export product for ethnic markets." },
    notes: "Also exported in processed forms like powder and oil.",
  },
  {
    id: "sunflower-seeds",
    name: "Sunflower Seeds",
    hsCode: "12060090",
    category: "Oilseeds",
    subCategory: "Seeds",
    images: {
      cover: "/placeholder.svg?height=600&width=800",
      gallery: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    },
    summary: "Nutritious sunflower seeds, used for high-quality oil extraction and as a healthy snack. A good source of vitamin E and healthy fats.",
    specs: {
      grade: "A-Grade",
      keyParameters: {
        moisture: "9% max",
        purityOrActives: "Purity 99% min, Oil content 42% min",
        defects: "Damaged seeds < 3%",
        foreignMatter: "< 1%",
      },
      compliance: {
        marketMRLs: ["Europe", "Asia"],
        gmo: "Non-GMO",
        allergens: "None",
      },
    },
    origin: { country: "India", region: "Karnataka, Maharashtra, Andhra Pradesh" },
    packaging: {
      options: ["25kg, 50kg PP bags"],
      palletization: true,
      containerLoadability: { "20ft": 18, "40ft": 25 },
    },
    trade: {
      moq: "18 MT",
      leadTime: "15-20 days",
      incoterms: ["FOB Chennai/JNPT", "CIF"],
      paymentTerms: ["LC, TT"],
      inspection: "Third-party inspection",
      documents: ["Standard export documents"],
    },
    certifications: ["APEDA"],
    shelfLife: "12 months",
    storage: "Store in cool, dry conditions to prevent rancidity.",
    capabilities: { privateLabel: true, monthlyCapacityMT: 1000, samples: "Available (500g)" },
    pricing: { currency: "USD", basis: ["FOB", "CIF"], priceOnRequest: true, notes: "Price varies for confectionary (snacking) and oil-crushing grades." },
    notes: "Both hulled (kernels) and in-shell seeds are available.",
  },

];

export const products = productsData.map(
  (data) =>
    new Product(
      data.id,
      data.name,
      data.hsCode,
      data.category,
      data.subCategory,
      data.images,
      data.summary,
      data.specs,
      data.origin,
      data.packaging,
      data.trade,
      data.certifications,
      data.shelfLife,
      data.storage,
      data.capabilities,
      data.pricing,
      data.notes,
    ),
)

export const getProductById = (id: string): Product | undefined => {
  return products.find((product) => product.id === id)
}

export const getProductsByCategory = (category: string): Product[] => {
  return products.filter((product) => product.category === category)
}

export const getAllCategories = (): string[] => {
  return Array.from(new Set(products.map((product) => product.category)))
}

export const searchProducts = (query: string): Product[] => {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery) ||
      product.summary.toLowerCase().includes(lowercaseQuery) ||
      product.hsCode.includes(lowercaseQuery),
  )
}
